### ISSUE TITLE
Binancer not available for R 3.6.3

### ISSUE THREAD

**Issue by BlueSkyTrading** [daroczig/binancer#13]
Hi,

when I try to install your package, I get this message:

```
Warning in install.packages :
  package ‘binancer’ is not available (for R version 3.6.3)

Warning message:
  there is no package called ‘binancer’
```

**Comment by PatronMaster** [comment]
Hi BlueSkyTrading,

This is a package outside of CRAN.
So, you need install by git.

Example:
```
library(devtools)
install_github(" daroczig/binancer")

```
This is amazing package. You also need create your API in Binance if you are trying to trade.
Also, I recommend you to Update your R for last version.

**Comment by daroczig** [comment]
Thanks a lot, @PatronMaster, for the above pointers.
