### ISSUE TITLE
Cannot find this package in CRAN

### ISSUE THREAD

**Issue by waynelapierre** [daroczig/binancer#15]
Has this package been registered on CRAN?  I could not find it.

**Comment by PatronMaster** [comment]
Hi Waynelapierre,

This is a package outside of CRAN.

So, you need install by git.

Example:

```
library(devtools)
install_github(" daroczig/binancer")
```
This is amazing package. You also need create your API in Binance if you are trying to trade.

**Comment by waynelapierre** [comment]
I am actually looking for the manual. Since it is not on CRAN, there is no manual...

**Comment by daroczig** [comment]
I can work on this over the weekend.

**Comment by daroczig** [comment]
@waynelapierre meanwhile you can find the manual at https://daroczig.github.io/binancer/reference/index.html

**Comment by daroczig** [comment]
https://cran.r-project.org/package=binancer
