### ISSUE TITLE
Error with binance_query()

### ISSUE THREAD

**Issue by timothyjgraham** [daroczig/binancer#17]
Hi all,

I am running the latest Github version of 'binancer' and when I check my account with `binance_account()` it gives the following error:

```
Error in binance_query(endpoint = "api/v3/account", sign = TRUE) : 
  -1021 Timestamp for this request is outside of the recvWindow.
```

Can anyone please help?

**Comment by mvolar** [comment]
Your system time is out of date, you have to google "syncing up system time" fro your system of choice.

**Comment by daroczig** [comment]
Thanks, @mvolar! @timothyjgraham, hopeful the above makes sense.
Closing, but please reopen if you think there's a related problem in the package.
