### ISSUE TITLE
New_order error

### ISSUE THREAD

**Issue by 1tomdawson** [daroczig/binancer#20]
When submitting a new order

```
binance_new_order("CHRUSDT", side = "BUY", type = "LIMIT", quantity = 40,     price = bidask$bid_price, time_in_force = 'GTC') 

```

I get this back

```

TEST
   ord
1:  OK

```
It does not complete the order and I dont understand why? Thanks for any advise.

**Comment by nguyenngocbinh** [comment]
I also meet this error. Test result is still ok, but dont have any orders.

**Comment by Fayorsey** [comment]
You need to specify test = F 

` binance_new_order(symbol = symbol, side = 'BUY', type = 'LIMIT', time_in_force = 'GTC', price = lastPrice, quantity = quantity,  test = F)`
