### ISSUE TITLE
Error in binance_mytrades()

### ISSUE THREAD

**Issue by PatronMaster** [daroczig/binancer#3]
You have an error in binance_mytrades(), you write setnames instead of setNames.

Amazing job. Thanks 
Now I need 1 week to understand all this code.

**Comment by YsoSirius** [comment]
`setnames` is correct. Its a function from the `data.table` package.
This just formats the column names of the table to lower case and adds a "_" between words.

**Comment by daroczig** [comment]
Sorry for the late reply -- did not get notified of these tickets.
@YsoSirius is correct, using `setnames` from `data.table` is on purpose instead of `setNames` -- although it seems it's not imported correctly, so fixing it
