### ISSUE TITLE
Add startTime and endTime to get_klines

### ISSUE THREAD

**Issue by johnatasjmo** [daroczig/binancer#4]
get_klines function optional parameters to be added are startTime and endTime.

As per: https://www.binance.com/restapipub.html#user-content-general-endpoints

**Comment by YsoSirius** [comment]
link is down

**Comment by johnatasjmo** [comment]
https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md

**Comment by daroczig** [comment]
Sorry, I missed the notifications in this repo -- pushed an update above
