### ISSUE TITLE
Add timeout option

### ISSUE THREAD

**Issue by dimitry-ishenko** [daroczig/binancer#7]
With an unreliable connection calls to `binance_klines()` will sometimes hang and never return. The `httr` package supports `timeout()` option for the `GET()` function: https://rdrr.io/cran/httr/man/timeout.html

Ideally this option would be exposed in `binancer` or at least a sane default chosen (if there is one :smile: )

**Comment by daroczig** [comment]
Sorry for the long delay with this :/ 
Some updates just went out with better error handling -- can you please check if it's still an issue?

**Comment by dimitry-ishenko** [comment]
Feel free to close. I've moved on
